import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const routePath = fileURLToPath(new URL("./page.tsx", import.meta.url));
const loadingRoutePath = fileURLToPath(new URL("./loading.tsx", import.meta.url));
const componentPath = fileURLToPath(new URL("../../components/message/message-page.tsx", import.meta.url));
const dataPath = fileURLToPath(new URL("../../data/messages.ts", import.meta.url));
const inputRulesPath = fileURLToPath(new URL("../../lib/message-input.ts", import.meta.url));
const modelPath = fileURLToPath(new URL("../../features/rolling-paper/model.ts", import.meta.url));
const apiRoutePath = fileURLToPath(new URL("../api/letters/route.ts", import.meta.url));
const stylesPath = fileURLToPath(new URL("../../styles/globals.css", import.meta.url));
const bodyLimitMigrationPath = fileURLToPath(
  new URL("../../../supabase/migrations/20260916000100_expand_public_letter_body_limit.sql", import.meta.url),
);

assert.equal(existsSync(routePath), true, "message route should exist");
assert.equal(existsSync(loadingRoutePath), true, "message loading route should exist");
assert.equal(existsSync(componentPath), true, "message page component should exist");
assert.equal(existsSync(dataPath), true, "message data should exist");
assert.equal(existsSync(inputRulesPath), true, "message input rules should exist");
assert.equal(existsSync(modelPath), true, "rolling-paper model should exist");
assert.equal(existsSync(apiRoutePath), true, "letters API route should exist");
assert.equal(existsSync(stylesPath), true, "global styles should exist");
assert.equal(existsSync(bodyLimitMigrationPath), true, "150-character database migration should exist");

const route = readFileSync(routePath, "utf8");
const loadingRoute = readFileSync(loadingRoutePath, "utf8");
const component = readFileSync(componentPath, "utf8");
const data = readFileSync(dataPath, "utf8");
const styles = readFileSync(stylesPath, "utf8");
const apiRoute = readFileSync(apiRoutePath, "utf8");
const bodyLimitMigration = readFileSync(bodyLimitMigrationPath, "utf8");
const { messages } = await import(dataPath);
const {
  getMessageUsage,
  MESSAGE_LINE_BREAK_WEIGHT,
  MESSAGE_MAX_LENGTH,
  normalizeMessageBody,
} = await import(inputRulesPath);

assert.equal(MESSAGE_MAX_LENGTH, 150);
assert.equal(MESSAGE_LINE_BREAK_WEIGHT, 20);
assert.equal(normalizeMessageBody("첫 줄\r\n둘째 줄"), "첫 줄\n둘째 줄");
assert.equal(getMessageUsage("가\n나"), 22);
assert.equal(normalizeMessageBody("1\n2\n3\n4\n5\n6\n7\n8"), "1\n2\n3\n4\n5\n6\n7\n8");
assert.ok(getMessageUsage(normalizeMessageBody("가".repeat(140))) <= MESSAGE_MAX_LENGTH);
assert.ok(getMessageUsage(normalizeMessageBody("\n".repeat(20))) <= MESSAGE_MAX_LENGTH);

assert.match(route, /MessagePage/);
assert.match(route, /getPublicLetters/);
assert.match(route, /export const dynamic = "force-dynamic"/);
assert.match(route, /initialMessages=\{initialMessages\}/);
assert.match(route, /initialError=\{initialError\}/);
assert.match(component, /message-page/);
assert.match(component, /<h1 className="sr-only" id="message-page-title">GUESTBOOK<\/h1>/);
assert.doesNotMatch(component, />MESSAGE<\/h1>/);
assert.match(component, /initialMessages: Letter\[\]/);
assert.match(component, /useState<Letter\[\]>\(\(\) =>[\s\S]*initialMessages[\s\S]*\.sort/);
assert.match(component, /messageList\.map/);
assert.match(component, /Date\.parse\(a\.createdAt\) - Date\.parse\(b\.createdAt\)/);
assert.match(component, /setMessageList\(\(current\) => \[[\s\S]*\.\.\.current\.filter[\s\S]*payload\.letter!/);
assert.match(component, /To\./);
assert.match(component, /From\./);
assert.match(component, /useState<Recipient>\(DEFAULT_RECIPIENT\)/);
assert.match(component, /message-form__recipient-arrow\$\{isRecipientOpen/);
assert.match(component, /onClick=\{\(\) => setIsRecipientOpen/);
assert.match(component, /message-form__field--to\$\{isRecipientOpen/);
assert.match(component, /message-confirm-modal/);
assert.match(component, /fetch\("\/api\/letters"/);
assert.match(component, /method: "POST"/);
assert.match(component, /isSubmitting \? "전하는 중" : "메시지 전하기"/);
assert.match(component, /message-list-status/);
assert.doesNotMatch(component, /메시지를 불러오는 중입니다/);
assert.doesNotMatch(component, /cache: "no-store"/);
assert.match(loadingRoute, /isInitialLoading/);
assert.match(component, /message-card--skeleton/);
assert.match(component, /aria-busy=\{isInitialLoading\}/);
assert.match(component, /<form className="message-form" inert=\{isInitialLoading\}/);
assert.doesNotMatch(component, /id: Date\.now\(\)/);
assert.match(component, /message-form__validation/);
assert.match(component, /missingFields/);
assert.match(component, /message-frame-tab-mobile/);
assert.match(component, /message-frame-mobile/);
assert.match(component, /여러분의 한마디가 42회 졸업전시를 더 뜨겁게 완성합니다/);
assert.doesNotMatch(component, /○○회/);
assert.match(component, /getMessageUsage,[\s\S]*MESSAGE_MAX_LENGTH,[\s\S]*normalizeMessageBody/);
assert.match(component, /normalizeMessageBody\(event\.target\.value\)/);
assert.match(component, /\{getMessageUsage\(body\)\} \/ \{MESSAGE_MAX_LENGTH\}/);
assert.doesNotMatch(component, /· 줄바꿈/);
assert.match(component, /maxLength=\{MESSAGE_MAX_LENGTH\}/);
assert.doesNotMatch(component, /event\.target\.value\.slice\(0, MESSAGE_MAX_LENGTH\)/);
assert.match(component, /메시지는 화면 사용량 기준 최대 \{MESSAGE_MAX_LENGTH\}자까지 입력할 수 있습니다/);
assert.match(component, /message-form__counter/);
assert.doesNotMatch(component, /\{body\.length\}\s*\/\s*\{MESSAGE_MAX_LENGTH\}/);
assert.match(component, /message-character-count/);
assert.match(component, /message-card__recipient-name/);
assert.match(component, /useRef<HTMLElement>\(null\)/);
assert.match(component, /data-message-reveal/);
assert.match(component, /data-message-visible="false"/);
assert.doesNotMatch(component, /data-message-density|getMessageDensity/);
assert.doesNotMatch(component, /<form className="message-form" data-message-reveal/);
assert.match(component, /new IntersectionObserver/);
assert.match(component, /rootMargin: "0px 0px -8%"/);
assert.match(component, /prefers-reduced-motion: reduce/);
assert.match(component, /message-form__recipient-name/);
assert.match(component, /message-form__recipient-trigger\$\{to !== DEFAULT_RECIPIENT \? " is-selected" : ""\}/);
assert.doesNotMatch(component, /message-page__frame-backdrop/);
assert.match(data, /철수야 졸업 축하해/);
assert.ok(messages.every(({ body }) => body.length <= 150), "mock messages must stay within the 150 character limit");
assert.ok(new Set(messages.map(({ body }) => body)).size >= 6, "mock messages should show varied copy");
assert.ok(messages.filter(({ body }) => body.includes("\n")).length >= 6, "mock messages should include varied line breaks");
assert.match(styles, /\.message-page/);
assert.match(styles, /\.message-card/);
assert.match(styles, /\.message-list\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/);
assert.match(styles, /\.message-list\s*\{[\s\S]*column-gap:\s*47px;[\s\S]*row-gap:\s*50px;/);
assert.match(styles, /\.message-card\s*\{[\s\S]*padding:\s*30\.573px 40\.267px;/);
assert.match(styles, /\.message-card__copy\s*\{[\s\S]*gap:\s*15px;/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*font-size:\s*20px;[\s\S]*font-weight:\s*500;/);
assert.match(styles, /\.message-list\s*\{[\s\S]*--message-card-stagger:\s*clamp\(7rem, 7\.1vw, 8\.5rem\);[\s\S]*padding-bottom:\s*var\(--message-card-stagger\)/);
assert.match(styles, /\.message-card:nth-child\(4n \+ 2\),\s*\.message-card:nth-child\(4n \+ 4\)\s*\{[\s\S]*transform:\s*translateY\(var\(--message-card-stagger\)\)/);
assert.match(styles, /@media \(min-width: 1150px\) and \(max-width: 1599px\)[\s\S]*\.message-card:nth-child\(3n \+ 2\)\s*\{[\s\S]*transform:\s*translateY\(var\(--message-card-stagger\)\)/);
assert.match(styles, /@media \(max-width: 1149px\)[\s\S]*\.message-card:nth-child\(2n\)\s*\{[\s\S]*transform:\s*translateY\(var\(--message-card-stagger\)\)/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-list\s*\{[\s\S]*--message-card-stagger:\s*clamp\(3\.5rem, 13vw, 4\.875rem\)/);
assert.match(styles, /\.message-page__intro\s*\{[\s\S]*overflow:\s*visible/);
assert.match(styles, /\.message-list-container\s*\{[\s\S]*--message-list-lift:\s*clamp\(12rem, 18vw, 15rem\);[\s\S]*margin-top:\s*calc\(-1 \* var\(--message-list-lift\)\)/);
assert.match(styles, /\.message-list-container\s*\{[\s\S]*--message-list-footer-gap:\s*clamp\(6\.25rem, 8vw, 10rem\);[\s\S]*padding-bottom:\s*var\(--message-list-footer-gap\)/);
assert.match(styles, /@media \(min-width: 37\.5625rem\) and \(max-width: 63\.75rem\)[\s\S]*\.message-list-container\s*\{[\s\S]*--message-list-lift:\s*clamp\(3rem, 10vw, 6rem\)/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-list-container\s*\{[\s\S]*--message-list-lift:\s*clamp\(2rem, 8vw, 3rem\)/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-list-container\s*\{[\s\S]*--message-list-footer-gap:\s*4rem/);
assert.match(styles, /\.message-card\s*\{[\s\S]*container-type:\s*inline-size/);
assert.match(styles, /\.message-card\s*\{[\s\S]*padding:\s*clamp\(15px, 8%, 32px\) clamp\(20px, 10%, 40px\)/);
assert.doesNotMatch(styles, /data-message-density/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*font-size:\s*17px;[\s\S]*-webkit-line-clamp:\s*11/);
assert.match(styles, /@media \(min-width: 768px\) and \(max-width: 1020px\)[\s\S]*font-size:\s*15px;[\s\S]*-webkit-line-clamp:\s*11/);
assert.match(styles, /@media \(min-width: 700px\) and \(max-width: 767px\)[\s\S]*font-size:\s*14px;[\s\S]*-webkit-line-clamp:\s*11/);
assert.match(styles, /@media \(min-width: 601px\) and \(max-width: 699px\)[\s\S]*font-size:\s*12px;[\s\S]*-webkit-line-clamp:\s*10/);
assert.match(styles, /@media \(min-width: 501px\) and \(max-width: 600px\)[\s\S]*font-size:\s*10px;[\s\S]*-webkit-line-clamp:\s*9/);
assert.match(styles, /@media \(min-width: 401px\) and \(max-width: 500px\)[\s\S]*font-size:\s*8px;[\s\S]*-webkit-line-clamp:\s*9/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*font-size:\s*7px;[\s\S]*-webkit-line-clamp:\s*11/);
assert.match(bodyLimitMigration, /char_length\(body\) between 1 and 150/);
assert.match(styles, /@media \(min-width: 1150px\) and \(max-width: 1599px\)[\s\S]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(styles, /@media \(max-width: 1149px\)[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-card__to,[\s\S]*\.message-card__from\s*\{[\s\S]*font-size:\s*clamp\(9px, 5cqi, 10\.5px\)/);
assert.match(styles, /--message-form-width/);
assert.match(styles, /clamp\(2rem, 3\.4375vw, 4\.125rem\)/);
assert.match(styles, /\.message-form__field\s*\{[\s\S]*inset:\s*0/);
assert.match(styles, /\.message-form__field\s*\{[\s\S]*pointer-events:\s*none/);
assert.match(styles, /\.message-page \.site-footer\s*\{[\s\S]*z-index:\s*5/);
assert.match(styles, /Mobile coordinates are also measured from the complete form canvas/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*white-space:\s*pre-wrap/);
assert.match(styles, /\.message-form__validation/);
assert.match(styles, /\.message-list-status/);
assert.match(styles, /\.message-card--skeleton/);
assert.match(styles, /@keyframes message-skeleton-pulse/);
assert.match(styles, /\.message-confirm-modal__error/);
assert.match(styles, /\.message-confirm-modal__panel\s*\{[\s\S]*?width:\s*min\(500px, 100%\);[\s\S]*?padding:\s*42px 36px;/);
assert.match(styles, /@media \(max-width: 1020px\)[\s\S]*?\.message-confirm-modal__panel\s*\{[\s\S]*?width:\s*min\(460px, 100%\);[\s\S]*?padding:\s*36px 28px;/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*?\.message-confirm-modal__panel\s*\{[\s\S]*?width:\s*min\(440px, 100%\);[\s\S]*?padding:\s*32px 20px;/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*?\.message-confirm-modal__panel\s*\{[\s\S]*?width:\s*min\(320px, 100%\);[\s\S]*?padding:\s*26px 16px;/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*?\.message-confirm-modal__copy h2\s*\{[\s\S]*?font-size:\s*18px;/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*?\.message-confirm-modal__copy p\s*\{[\s\S]*?font-size:\s*12px;/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*?\.message-confirm-modal__actions button\s*\{[\s\S]*?font-size:\s*14px;/);
assert.match(styles, /\.message-form__counter/);
assert.doesNotMatch(styles, /\.message-form__body:focus-within/);
assert.match(styles, /font-size:\s*clamp\(1rem, 1\.042vw, 1\.25rem\)/);
assert.match(styles, /font-size:\s*clamp\(0\.75rem, 1\.3vw, 0\.875rem\)/);
assert.match(styles, /font-size:\s*clamp\(0\.5625rem, 2\.1vw, 0\.75rem\)/);
assert.match(styles, /\.message-page\[data-message-motion-ready="true"\] \[data-message-reveal\]\s*\{[\s\S]*opacity 620ms[\s\S]*translate 760ms/);
assert.match(styles, /\.message-list \.message-card\[data-message-visible="true"\]\s*\{[\s\S]*opacity: 1;[\s\S]*translate: 0 0;/);
assert.doesNotMatch(styles, /--message-card-layout-y|--message-card-motion-y/);
assert.match(styles, /\.message-card__recipient-name/);
assert.match(styles, /\.message-form__recipient-trigger\.is-selected[\s\S]*\.message-form__recipient-name/);
assert.match(styles, /\.message-form__recipient-arrow\.is-open\s*\{\s*transform:\s*rotate\(0deg\)/);
assert.match(styles, /\.message-form__field--to\s*>\s*span/);
assert.doesNotMatch(styles, /\.message-form__field--to span\s*\{/);
assert.match(styles, /\.message-form__recipient-name\s*\{[\s\S]*position:\s*static/);
assert.match(styles, /\.message-form__recipient-arrow\s*\{[\s\S]*position:\s*static/);
assert.match(styles, /\.message-form__recipient-trigger\s*\{[\s\S]*?font-size: 20px;[\s\S]*?font-weight: 400;/);
assert.match(styles, /\.message-form__recipient-menu button\s*\{[\s\S]*?font-size: 20px;[\s\S]*?font-weight: 400;/);
assert.match(styles, /max-width: 1350px/);
assert.match(styles, /max-width: 1020px/);
assert.match(styles, /max-width: 600px/);
assert.match(styles, /max-width: 400px/);
assert.match(apiRoute, /export async function GET/);
assert.match(apiRoute, /export async function POST/);
assert.match(apiRoute, /status: 201/);

console.log("message page structure checks passed");
