import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const routePath = fileURLToPath(new URL("./page.tsx", import.meta.url));
const componentPath = fileURLToPath(new URL("../../components/message/message-page.tsx", import.meta.url));
const dataPath = fileURLToPath(new URL("../../data/messages.ts", import.meta.url));
const stylesPath = fileURLToPath(new URL("../../styles/globals.css", import.meta.url));

assert.equal(existsSync(routePath), true, "message route should exist");
assert.equal(existsSync(componentPath), true, "message page component should exist");
assert.equal(existsSync(dataPath), true, "message data should exist");
assert.equal(existsSync(stylesPath), true, "global styles should exist");

const route = readFileSync(routePath, "utf8");
const component = readFileSync(componentPath, "utf8");
const data = readFileSync(dataPath, "utf8");
const styles = readFileSync(stylesPath, "utf8");
const { messages } = await import(dataPath);

assert.match(route, /MessagePage/);
assert.match(component, /message-page/);
assert.match(component, /messageList\.map/);
assert.match(component, /To\./);
assert.match(component, /From\./);
assert.match(component, /useState\("전체\(모두\)"\)/);
assert.match(component, /message-form__recipient-arrow\$\{isRecipientOpen/);
assert.match(component, /onClick=\{\(\) => setIsRecipientOpen/);
assert.match(component, /message-form__field--to\$\{isRecipientOpen/);
assert.match(component, /message-confirm-modal/);
assert.match(component, /message-form__validation/);
assert.match(component, /missingFields/);
assert.match(component, /message-frame-tab-mobile/);
assert.match(component, /message-frame-mobile/);
assert.match(component, /여러분의 한마디가 42회 졸업전시를 더 뜨겁게 완성합니다/);
assert.doesNotMatch(component, /○○회/);
assert.match(component, /const MESSAGE_MAX_LENGTH = 130/);
assert.match(component, /maxLength=\{MESSAGE_MAX_LENGTH\}/);
assert.match(component, /event\.target\.value\.slice\(0, MESSAGE_MAX_LENGTH\)/);
assert.match(component, /메시지는 최대 \{MESSAGE_MAX_LENGTH\}자까지 입력할 수 있습니다/);
assert.match(component, /message-form__counter/);
assert.match(component, /\{body\.length\}\s*\/\s*\{MESSAGE_MAX_LENGTH\}/);
assert.match(component, /message-character-count/);
assert.match(component, /message-card__recipient-name/);
assert.match(component, /message-form__recipient-name/);
assert.match(component, /message-form__recipient-trigger\$\{to !== DEFAULT_RECIPIENT \? " is-selected" : ""\}/);
assert.doesNotMatch(component, /message-page__frame-backdrop/);
assert.match(data, /철수야 졸업 축하해/);
assert.ok(messages.every(({ body }) => body.length <= 130), "mock messages must stay within the 130 character limit");
assert.ok(new Set(messages.map(({ body }) => body)).size >= 6, "mock messages should show varied copy");
assert.ok(messages.filter(({ body }) => body.includes("\n")).length >= 6, "mock messages should include varied line breaks");
assert.match(styles, /\.message-page/);
assert.match(styles, /\.message-card/);
assert.match(styles, /\.message-list\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/);
assert.match(styles, /\.message-list\s*\{[\s\S]*column-gap:\s*47px;[\s\S]*row-gap:\s*50px;/);
assert.match(styles, /\.message-card\s*\{[\s\S]*padding:\s*30\.573px 40\.267px;/);
assert.match(styles, /\.message-card__copy\s*\{[\s\S]*gap:\s*15px;/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*font-size:\s*20px;[\s\S]*font-weight:\s*500;/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*9;/);
assert.match(styles, /@media \(max-width: 1350px\)[\s\S]*\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*8;/);
assert.match(styles, /@media \(max-width: 1020px\)[\s\S]*\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*9;/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*7;/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*5;/);
assert.match(styles, /\.message-card:nth-child\(3n \+ 2\)/);
assert.match(styles, /\.message-page__intro\s*\{[\s\S]*overflow:\s*visible/);
assert.match(styles, /--message-form-width/);
assert.match(styles, /clamp\(2rem, 3\.4375vw, 4\.125rem\)/);
assert.match(styles, /\.message-form__field\s*\{[\s\S]*inset:\s*0/);
assert.match(styles, /\.message-form__field\s*\{[\s\S]*pointer-events:\s*none/);
assert.match(styles, /\.message-page \.site-footer\s*\{[\s\S]*z-index:\s*5/);
assert.match(styles, /Mobile coordinates are also measured from the complete form canvas/);
assert.match(styles, /\.message-card__body\s*\{[\s\S]*white-space:\s*pre-wrap/);
assert.match(styles, /\.message-form__validation/);
assert.match(styles, /\.message-form__counter/);
assert.doesNotMatch(styles, /\.message-form__body:focus-within/);
assert.match(styles, /font-size:\s*clamp\(1rem, 1\.042vw, 1\.25rem\)/);
assert.match(styles, /font-size:\s*clamp\(0\.75rem, 1\.3vw, 0\.875rem\)/);
assert.match(styles, /font-size:\s*clamp\(0\.5625rem, 2\.1vw, 0\.75rem\)/);
assert.match(styles, /@media \(min-width: 1350\.0625px\)[\s\S]*\.message-card__body\s*\{[\s\S]*font-size:\s*22px;[\s\S]*-webkit-line-clamp:\s*8;/);
assert.match(styles, /@media \(max-width: 600px\)[\s\S]*\.message-card__body\s*\{[\s\S]*font-size:\s*clamp\(0\.8125rem, 2\.5vw, 0\.9375rem\)/);
assert.match(styles, /@media \(max-width: 400px\)[\s\S]*\.message-card__body\s*\{[\s\S]*-webkit-line-clamp:\s*6;/);
assert.match(styles, /\.message-card__recipient-name/);
assert.match(styles, /\.message-form__recipient-trigger\.is-selected[\s\S]*\.message-form__recipient-name/);
assert.match(styles, /\.message-form__recipient-arrow\.is-open\s*\{\s*transform:\s*rotate\(0deg\)/);
assert.match(styles, /\.message-form__field--to\s*>\s*span/);
assert.doesNotMatch(styles, /\.message-form__field--to span\s*\{/);
assert.match(styles, /\.message-form__recipient-name\s*\{[\s\S]*position:\s*static/);
assert.match(styles, /\.message-form__recipient-arrow\s*\{[\s\S]*position:\s*static/);
assert.match(styles, /\.message-form__recipient-trigger\s*\{[\s\S]*?font-size: 20px;[\s\S]*?font-weight: 400;/);
assert.match(styles, /\.message-form__recipient-menu button\s*\{[\s\S]*?font-size: 20px;[\s\S]*?font-weight: 400;/);
assert.match(styles, /max-width: 1350px/);
assert.match(styles, /max-width: 1020px/);
assert.match(styles, /max-width: 600px/);
assert.match(styles, /max-width: 400px/);

console.log("message page structure checks passed");
