"""Rebuild motion-ready SVGs from the checked-in Figma vectors (no raster editing)."""
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NS = 'http://www.w3.org/2000/svg'
ET.register_namespace('', NS)

# Frame origins and fuse bounds measured from the source SVG coordinate space.
SCENES = [
    (1920, 1340, -31, -255, 1506.4, 358, 190.48),
    (1350, 900, -67, -187, 987.091, 234.585, 124.819),
    (1020, 1370, -29, -210, 514.639, 379.999, 196.146),
    (600, 980, -7.94922, -144.359, 314.465, 294.827, 138.210),
    (400, 860, 0, -116, 209.522, 244, 103.407),
]

def element(tag, **attrs):
    return ET.Element(f'{{{NS}}}{tag}', {k: str(v) for k, v in attrs.items()})

scenes = []
for width, height, ox, oy, tx, ty, tw in SCENES:
    svg = ET.parse(ROOT / f'public/assets/figma/main-artwork-{width}.svg').getroot()
    svg.set('viewBox', f'{ox} {oy} {width} {height}')
    svg.set('width', str(width))
    svg.set('height', str(height))
    svg.set('class', 'hero-scene-svg')
    svg.set('focusable', 'false')
    by_id = {e.get('id'): e for e in svg.iter() if e.get('id')}
    main = by_id['Main']
    # These first two paths are the Figma editor canvas, not exhibition artwork.
    for child in list(main)[:2]:
        main.remove(child)
    by_id['Group_4'].set('class', 'hero-ignite')
    by_id['Group 366'].set('class', 'hero-lion')
    for index, name in enumerate(['Group', 'Group_2', 'Group_3']):
        by_id[name].set('class', f'hero-burst hero-burst-{index}')
    tail = by_id['Group_12']
    tail.set('class', 'hero-fuse')
    scale = tw / 190.48
    # Centre line follows the original curled fuse from its lit tip into the body.
    points = [(32,72),(46,42),(88,20),(127,24),(166,43),(169,76),(153,115),(137,154)]
    p = [(tx+x*scale, ty+y*scale) for x,y in points]
    d = f'M {p[0][0]} {p[0][1]} C {p[1][0]} {p[1][1]} {p[2][0]} {p[2][1]} {p[3][0]} {p[3][1]} S {p[4][0]} {p[4][1]} {p[5][0]} {p[5][1]} Q {p[6][0]} {p[6][1]} {p[7][0]} {p[7][1]}'
    defs = next(e for e in svg if e.tag.endswith('defs'))
    mask = element('mask', id='fuse-mask', maskUnits='userSpaceOnUse', x=tx-100*scale, y=ty-100*scale, width=400*scale, height=400*scale)
    mask.append(element('rect', x=tx-100*scale, y=ty-100*scale, width=400*scale, height=400*scale, fill='white'))
    erase = element('path', d=d, pathLength=100, fill='none', stroke='black', **{'stroke-width':76*scale,'stroke-linecap':'butt','class':'hero-fuse-erase'})
    mask.append(erase)
    # Remove the original tip flame as the moving flame takes over.
    mask.append(element('circle', cx=p[0][0], cy=p[0][1], r=40*scale, fill='black', **{'class':'hero-fuse-tip-erase'}))
    defs.append(mask)
    tail.set('mask', 'url(#fuse-mask)')
    spark = element('g', **{'class':'hero-fuse-spark','style':f'offset-path:path("{d}");offset-rotate:0deg;offset-anchor:0px 0px'})
    star = '0,-19 5,-7 17,-13 10,-2 23,3 8,7 10,20 0,11 -12,20 -8,5 -23,1 -9,-5 -15,-16 -3,-10'
    spark.append(element('polygon', points=star, fill='#FD9519', transform=f'scale({scale})'))
    spark.append(element('polygon', points=star, fill='#FCD519', transform=f'scale({scale*.62})'))
    by_id['Group_11'].append(spark)
    # Local, short-lived flecks follow the final ignition; no canvas particles/timers.
    debris = element('g', transform=f'translate({p[-1][0]} {p[-1][1]}) scale({scale})')
    for i, (dx,dy) in enumerate([(-85,-60),(-35,-110),(45,-95),(100,-30),(70,65),(-70,60)]):
        piece=element('path', d='M -5 -4 L 7 -2 L 2 7 L -7 3 Z', fill=['#FCD519','#FD9519','#41C9F9'][i%3], **{'class':'hero-paint-fleck','style':f'--fleck-x:{dx}px;--fleck-y:{dy}px;--fleck-r:{i*53}deg'})
        debris.append(piece)
    by_id['Group 366'].append(debris)
    # Namespace every ID because all responsive scenes share one document.
    markup = ET.tostring(svg, encoding='unicode')
    ids=re.findall(r'id="([^"]+)"',markup)
    for ident in ids:
        replacement=f'hero-{width}-{ident.replace(" ", "-")}'
        markup=markup.replace(f'id="{ident}"',f'id="{replacement}"').replace(f'url(#{ident})',f'url(#{replacement})')
    scenes.append({'width':width,'height':height,'markup':markup})

target=ROOT/'src/components/main/hero-scenes.generated.ts'
target.write_text('// Generated by scripts/generate-hero-motion.py. Do not hand-edit.\nexport const heroScenes = '+json.dumps(scenes,ensure_ascii=False,indent=2)+' as const;\n')
