create table if not exists public.public_letters (
  id bigint generated by default as identity primary key,
  recipient text not null check (char_length(recipient) between 1 and 20),
  sender text not null check (char_length(sender) between 1 and 20),
  body text not null check (char_length(body) between 1 and 130),
  created_at timestamptz not null default now(),
  hidden_at timestamptz
);

create index if not exists public_letters_visible_created_at_idx
  on public.public_letters (created_at desc)
  where hidden_at is null;

create table if not exists public.public_letter_submission_attempts (
  id bigint generated by default as identity primary key,
  client_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists public_letter_submission_attempts_lookup_idx
  on public.public_letter_submission_attempts (client_hash, created_at desc);

alter table public.public_letters enable row level security;
alter table public.public_letter_submission_attempts enable row level security;

create or replace function public.create_public_letter(
  p_recipient text,
  p_sender text,
  p_body text,
  p_client_hash text
)
returns setof public.public_letters
language plpgsql
security definer
set search_path = public
as $$
declare
  created_letter public.public_letters;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_client_hash, 0));

  if (
    select count(*)
    from public.public_letter_submission_attempts
    where client_hash = p_client_hash
      and created_at >= now() - interval '10 minutes'
  ) >= 5 then
    raise exception 'LETTER_RATE_LIMITED' using errcode = 'P0001';
  end if;

  insert into public.public_letter_submission_attempts (client_hash)
  values (p_client_hash);

  insert into public.public_letters (recipient, sender, body)
  values (p_recipient, p_sender, p_body)
  returning * into created_letter;

  return next created_letter;
end;
$$;

revoke all on table public.public_letters from anon, authenticated;
revoke all on table public.public_letter_submission_attempts from anon, authenticated;
revoke all on function public.create_public_letter(text, text, text, text) from public, anon, authenticated;
grant select on table public.public_letters to service_role;
grant execute on function public.create_public_letter(text, text, text, text) to service_role;

comment on table public.public_letters is 'Public rolling-paper messages. hidden_at is used for soft moderation.';
comment on table public.public_letter_submission_attempts is 'Hashed request fingerprints used only for rolling-window rate limiting.';
